config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'sports-news', to: 'pages#sports_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mt-auto text-white-50">
    <p><%= @copyright%></p>
</footer>

app/views/shared/_application_nav.html.erb
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Austin McCombs</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end app-nav">  
        <%= nav_helper 'nav-link', 'span' %>
        <%= login_helper 'nav-link'%>
      </nav>
    </div>
  </header>
 

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
        <p> <%= @copyright %></p>
        <p>
          <a href="#">Back to top</a>
        </p>
</footer>

app/views/shared/_blog_masthead.html.erb
 <div class = 'blog header'>
      <div class = 'container'>
        <h1 class = 'blog-title'>My Blog</h1>
        </br>
        <span>
            <%= link_to 'Write a New Blog', new_blog_path, 
        class: 'btn btn-secondary btn-outline-warning' if logged_in?(:site_admin) %>
        </span>

        <span>
          <%= link_to 'Topics', topics_path, class: 'btn btn-warning btn-outline-secondary' %>
        </span>
        </br>
      </div>
</div>

app/views/shared/_blog_nav.html.erb
  <div class = 'container'>
    <div class="nav-scroller py-1 mb-2">
      <nav class="nav d-flex justify-content-between">
          <%= nav_helper 'p-2 link-secondary', 'span' %>
          <%= login_helper 'p-2 link-secondary'%>
      </nav>
    </div>
  </div>

 

app/views/shared/_blog_sidebar.html.erb
<div class="col-md-4">
          <div class="p-4 mb-3 bg-dark rounded">
            <h4 class="font-italic">About Me</h4>
            <p class="mb-0">Passionate about all things technology and sports. I've worked in QA for just over 4
            years now and am looking to take that knowledge of helping to create quality software
            and transition into a web developer role.</p>
          </div>
          <div class = 'p-4'>
            <h4>Topics</h4>
            <% @side_bar_topics.each do |topic| %>
              <p><%= link_to topic.title, topic_path(topic) %></p>
            <% end %>
          </div>
      
          <%= render 'shared/socials' %>
</div>

app/views/shared/_latest_content.html.erb
<div class = 'container space-top latest-stuff'>
      <h2 class = 'text-center space-top text-yellow'>Whats New?</h2>
      <div class = 'row space-top'>
        <div class = 'col-md-5'>
          <div class = 'card-body'>
            <h4 class = 'text-center text-yellow'><%= link_to @latest_blog.title, blogs_path%></h4>
            <p class = 'text-white truncated'><%= @latest_blog.body %></p>
          </div>
        </div>

        <div class = 'col-md-2'>

        </div>

        <div class = 'col-md-5'>
          <div class = 'card-body'>
            <h4 class = 'text-center text-yellow'><%= link_to @latest_proj.title, portfolios_path%></h4>
            <p class = 'text-white truncated'><%= @latest_proj.body %></p>
          </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-toggleable-lg bg-dark  nav-masthead">
  
  <div class="container-fluid">
    
    <div class="navbar-header">
      <a class="navbar-brand nav-brand" href="#">Austin McCombs</a>
    </div>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="" role="button" ><i class="fa fa-bars" aria-hidden="true" style="color:#e6e6ff"></i></span>
    </button>
    <div class = 'collapse navbar-collapse justify-content-center' id = 'collapsibleNavbar'>
    <ul class = 'nav navbar-nav mx-auto'>
       <%= nav_helper 'text-white nav-link nav navbar-nav navbar-left' %>
    </ul>
    <ul class = 'nav navbar-nav mx-auto'>
        <%= login_helper 'text-white nav-link'%>
     </ul>
     </div>
  </div>
</nav>

app/views/shared/_portfolio_footer.html.erb
<footer class="portfolio-footer">
        <p class="float-end mb-1">
        </p>
        <p class = 'link'>
            <%= @copyright %>
        </p>
</footer>

app/views/shared/_portfolio_masthead.html.erb
 <section class="py-5 text-center container masthead">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">My Portfolio</h1>
            <p class="lead">Check out my work! Here are some of my favorite projects.</p>
            <p>
              <%= link_to 'Find Out About Me', about_me_path, class: 'btn btn-outline-warning' %>
              <%= link_to 'Blogs', blogs_path, class: 'btn btn-warning' %>
            </p>
          </div>
        </div>
</section>

app/views/shared/_portfolio_nav.html.erb
   <header class="mb-auto bg-dark">
    <div>
      <h3 class="float-md-start mb-0 text-white">Austin McCombs</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end app-nav">  
        <%= nav_helper 'text-white', 'span' %>
        <%= login_helper 'text-white'%>
      </nav>
    </div>
  </header>


     

app/views/shared/_socials.html.erb
<div class="p-4 my-auto">
    <ol class="list-unstyled social-links">
        <li><a href='https://github.com/austinmccombs'><%= fa_icon "github" %></a></li>
        <li><a href='https://www.linkedin.com/in/austin-mccombs-99b647173/'><%= fa_icon "linkedin" %></a></li>
        <li><a href='https://www.twitter.com/austin_mccombs9'><%= fa_icon "twitter" %></a></li>
        <li><a href='https://www.instagram.com/austin_mccombs/'><%= fa_icon "instagram" %></a></li>
    </ol>
</div>