config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'sports-news', to: 'pages#sports_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/pages/about.html.erb
<div class = 'app-card-container'>
    
    <div class = 'card'>
        <h1>About Me </h1>

        <hr>

        <div class = 'row'>
            <div class = 'col-md-5'>
                <%= image_tag "profile_image.JPG", width: '100%', alt: 'profile image', class: 'profile-image' %>

                <div class ='skils'>
                    <% @skills.each do |skill| %>
                        <div class = 'skill'>
                            <h4><%= skill.title %></h4>
                            <div class='progress'>
                                <div 
                                    class='progress-bar progress-bar-striped bg-warning'
                                    role='progressbar'
                                    aria-valuenow='<%= skill.percent_utilized %> ' 
                                    aria-valuemax='100'
                                    style='width: <%= skill.percent_utilized %>%' 
                                >
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class = 'col-md-7'>
                <p>I have spent just under half a decade ensuring the quality of software put in front of the users.
                Ive recently decided to take that knowledge of what makes a good software product and shift my focus to helping
                build out those qualities.</p>

                <p>The ideal situation for me is coming into a high energy group that is passionate about what they do but also knows
                how to have a good time outside of work. An environment full of empathy where I'm able to learn and be mentored from 
                engineers who are as willing and excited to teach me as I am to learn from them. </p>

                <p> 
                    <button
                        class = 'btn btn-outline-warning'
                        type = 'button'
                        data-toggle='collapse'
                        data-target='#jobHistory'
                        aria-expanded='false'
                        aria-controller='jobHistory'
                    >
                    Job History 
                    </button>

                    <button
                        class = 'btn btn-outline-warning'
                        type = 'button'
                        data-toggle='collapse'
                        data-target='#education'
                        aria-expanded='false'
                        aria-controller='education'
                    >
                    Education 
                    </button>

                </p>

                <p>
                    <div class = 'collapse' id='jobHistory'>
                        <div class = 'card card-block bg-warning'>
                            <Span class = 'job-title'>QA Engineer</Span>
                            <Span class = 'job-company'>SimpleNexus</Span>
                            <Span class = 'job-date'>Oct. 2020 - Current</Span>
                        </div>
                        <div class = 'card card-block bg-warning'>
                            <Span class = 'job-title'>QA Team Lead</Span>
                            <Span class = 'job-company'>Alsco</Span>
                            <Span class = 'job-date'>Aug. 2019 - May 2020</Span>
                        </div>
                        <div class = 'card card-block bg-warning'>
                            <Span class = 'job-title'>QA Engineer</Span>
                            <Span class = 'job-company'>eFileCabinet</Span>
                            <Span class = 'job-date'>Jun. 2016 - Jun.2017, Jan. 2018 - Aug. 2019</Span>
                        </div>
                        
                    </div>

                    <div class = 'collapse' id='education'>
                        <div class = 'card card-block bg-warning'>
                            <span class = 'job-title'>Associates</span>
                            <span class = 'job-company'>Computer Science: Information Systems</span>
                            <span class = 'job-date'>Salt Lake Community College</span>
                        </div>
                         <div class = 'card card-block bg-warning'>
                            <span class = 'job-title'>Certificate</span>
                            <span class = 'job-company'>Full Stack Web Development</span>
                            <span class = 'job-date'>DevPointLabs</span>
                        </div>
                        <p class = 'text-yellow'>
                            <%= link_to fa_icon('download'), '2021_resume.pdf', download: '', class: 'resume'  %> Resume
                        </p>
                    </div>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/pages/contact.html.erb
<div class = 'app-card-container'>
    <div class = 'card'>

        <h1 class = 'text-center'>Lets Work Together</h1>

        <hr>
            <div class = "row">
                <div class="col-md-4 my-auto">
                    <p
                        data-toggle='collapse'
                        data-target='#location'
                        aria-expanded='false'
                        aria-controller='location' >
                        <%= fa_icon 'map-marker', class: 'icons contact-icons' %>
                    </p>
                    <div class = 'collapse' id = 'location'>
                        <p>Salt Lake City, Utah</p>
                    </div>
                    
                    <p
                        
                        data-toggle='collapse'
                        data-target='#phoneNumber'
                        aria-expanded='false'
                        aria-controller='phoneNumber' >
                        <%= fa_icon 'phone', class: 'icons contact-icons' %>
                    </p>
                    <div class = 'collapse' id='phoneNumber'>
                        <p><%= number_to_phone '3852589841' %></p>
                    </div>
                    
                    <p>
                        <a href="mailto:austinmccombs22@gmail.com?subject=PortfolioContact" "email me"><%= fa_icon 'envelope', class: 'icons contact-icons'%>
                    </p>

                </div>
                <div class="col-md-8">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3029.5194992532934!2d-112.02484324974034!3d40.59636045251876!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87528e49f5ded585%3A0xea5f21974c919147!2s8532%20Barnstable%20Dr%2C%20West%20Jordan%2C%20UT%2084081!5e0!3m2!1sen!2sus!4v1611209914034!5m2!1sen!2sus"
                     width = '300' height= '300' frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>

app/views/pages/home.html.erb
  <main class="px-3">
    <jumbotron class = 'bg-transparent text-center space-top text-yellow'>
      <div >
        <h1 class = 'icon-header'><%= fa_icon 'hand-rock' %></h1>
        <p class="lead skill">
          <span class = 'element space-top text-white'></span>
        </p>
        <p class="lead skill space-top">
          <%= link_to "About Me", about_me_path, class: 'btn btn-outline-warning space-top bg-dark' %>
        </p>
      </div>
    </jumbotron>

    <hr>
    
    <%= render 'shared/latest_content' %>
    
  </main>

app/views/pages/sports_news.html.erb
<div class = 'inner cover'>
    <div class = 'row news-header'>
        <div class = 'col-md-12'>
            <h1 class = 'cover-heading'>Sports News</h1>
        </div>
    </div>
    <div class = 'row news-header'>
        <div class = 'col-md-6 icons'>
            <%= link_to fa_icon('bicycle'), '', class: 'yellow-text' %>
        </div>
        <div class = 'col-md-6 icons'>
            <%= link_to fa_icon('code'), tech_news_path, class: 'yellow-text' %>
        </div>
    </div>
    <div class = 'row'>
        <% @sports.each do |sport| %>
            <div class = 'col-md-6'>
                <div class = 'tech-news'>
                    <div class = 'card'>
                        <%= twitter_parser sport %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/pages/tech_news.html.erb
<div class = 'inner cover'>
    <div class = 'row news-header'>
        <div class = 'col-md-12'>
            <h1 class = 'cover-heading'>Tech News</h1>
        </div>
    </div>
    <div class = 'row news-header'>
        <div class = 'col-md-6 icons'>
            <%= link_to fa_icon('bicycle'), sports_news_path, class: 'yellow-text' %>
        </div>
        <div class = 'col-md-6 icons'>
            <%= link_to fa_icon('code'), '', class: 'yellow-text' %>
        </div>
    </div>
    <div class = 'row'>
        <% @tweets.each do |tweet| %>
            <div class = 'col-md-6'>
                <div class = 'tech-news'>
                    <div class = 'card'>
                        <%= twitter_parser tweet %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>